### PR TITLE
Change the default for EXPLICIT_TEMPLATE_INSTANTIATION to ON

### PR DESCRIPTION
**Pull request by prwolfe**
This was motivated by Trilinos as it improves the
build and link time somewhat.

### CODE REVIEW

**Comment by prwolfe** [comment]
This replaces https://github.com/trilinos/Trilinos/pull/8333

**Comment by jmgate** [comment]
Will this switch ETI on for all TriBITS projects?  Just want to make sure that doesn't accidentally bite some team if they don't see it coming.

**Comment by prwolfe** [comment]
Yes - that's why I was unsure of where to place the change. If this is an issue please let me know!

**Comment by jmgate** [comment]
I would just check in with, e.g., @bathmatt for EMPIRE, @rppawlo for Drekar, and @glhenni for Charon to see how it might impact those codes.  Not sure about others.

**Comment by rppawlo** [comment]
@jmgate - Drekar is fine: all drekar devs use ETI=ON and testing enables it also.

**Comment by rppawlo** [comment]
@jmgate - since EMPIRE uses the ATDM build scripts, it is always using ETI-ON as well.

```
ATDM_SET_CACHE(Trilinos_ENABLE_EXPLICIT_INSTANTIATION ON CACHE BOOL)
```

https://github.com/trilinos/Trilinos/blob/d19a7c3cf9722aa441733c80f8e2dd39e001b5f4/cmake/std/atdm/ATDMDevEnvSettings.cmake#L289

**Comment by glhenni** [comment]
Charon has ETI on by default. I don't remember the last time I tried to build without it. Doesn't mean some packages we depend on won't break, but charon itself should be fine.

**Review by bartlettroscoe — APPROVED** [review]
Thanks @prwolfe!  I will go ahead and run the native TriBITS test suite, merge to TriBITS 'master', snapshot to the Trilinos 'tribits_github_snapshot' branch, and post a PR that merges that into 'develop'.

**Comment by bartlettroscoe** [comment]
@prwolfe and/or @jmgate, can one or both of you please review the updated documentation and release notes?

**Review by jmgate — APPROVED** [review]

**Comment by prwolfe** [comment]
Thanks guys!

**Pull request merged**
