### PR TITLE
Update copyright and license files

### PR DESCRIPTION
**Pull request by bartlettroscoe**
## Description

I did a few things here:

* Applied a patch from Curt Ober to the tribits/Copyright.txt file (see commit 026fd7d01cc4d06e7d94c0a60d7847a41f914f33)

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@ccober6, can you please take a look at the copyright and license files in this PR and see if they are to your liking?

**Review by ccober6 — APPROVED** [review]
LGTM.

Yeah, going with the new copyright and license works!  Just wanted to get rid of references to the old Sandia contract and make things consistent.  :)

**Comment by bartlettroscoe** [comment]
FYI: I moved the other changes to another branch so this PR just has updates the copyright files as requested.  I will create a different PR for the other unrelated changes (that I was making to get TriBITS test working locally on a RHEL8 machine with Clang and GNU).

**Review by rabartlett1972 — APPROVED** [review]
@ccober6 already signed off on this so I will let this merge so we can put this in Trilinos 'develop'.

**Pull request merged**
