### PR TITLE
Prune export libraries and package lists

### PR DESCRIPTION
**Pull request by nschloe**
This pull request cleans up the cluttered export variables.

In `TribitsWriteClientExportFiles.cmake`, great lengths are gone to capture the entire dependency tree of every single package. None of this is actually necessary: Much of the dependency handling can be done by CMake itself. There is much room for cleaning up the export functionality, and this pull request makes a start by creating leaner export files.

Fixes bug #32.

### CODE REVIEW

**Comment by nschloe** [comment]
Not sure at all what happened with this PR. Has history been rewritten at some point?

**Comment by bartlettroscoe** [comment]
Repo got filtered as part of #26, as per your request :-)

**Comment by nschloe** [comment]
Oh well, I suppose we'll have to filter my fork in the same way to make some sense of the existing PRs. Alternatively, I could try and go through the commits of mine and see if I can create a new PR from those.

**Comment by bartlettroscoe** [comment]
Can't you just create new branches by cherry-picking the commits?  Or, you can use `git format-path` and `git am` to move the commits.

**Comment by nschloe** [comment]
`cherry-pick`ing is probably the best idea. I'll just have to go through the above list and see what commits are actually meant to be in this PR.

**Comment by nschloe** [comment]
Closing in favor of PR #60.

**Pull request closed without merging**
