### PR TITLE
Recursive chgrp and chmod for install (#314)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Addresses #314

### CODE REVIEW

**Comment by jmgate** [comment]
@bartlettroscoe, how are things progressing here.  We are still seeing testing failures in our Trilinos sync, so we likely won't deploy for at least another day.

**Comment by bartlettroscoe** [comment]
> how are things progressing here

@jmgate, pretty close.  I just overlooked a couple of details that I am now addressing.  Should have a Trilinos PR by late morning.

**Comment by bartlettroscoe** [comment]
@jmgate,

FYI: This is finally done and I am in the process of pushing with checkin-test.py (and this PR will merge any second).

**Comment by jmgate** [comment]
Thanks @bartlettroscoe.  I appreciate all the effort put into it.

**Pull request merged**
