### PR TITLE
Transition to find_package(Python3) (#610)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
## Description

Addresses #610 

## Notes to reviewers

* Prefer to review this PR commit-by-commit
* There are some commits at the beginning that are not directly related to this change but were bundled with this PR to avoid extra overhead
* Please make sure and review the updated documentation and `CHANGELOG.md` files

### CODE REVIEW

**Comment by sebrowne** [comment]
RHEL8 has a default Python version of 3.6.8, so TriBITS projects + Python support will not work there.  RHEL9 has a default Python version of 3.9.18 so that's a-okay.  We have a large number of RHEL8 platforms, so that has the potential to cause issues.  How strong is the requirement for 3.8+?

**Comment by bartlettroscoe** [comment]
> RHEL8 has a default Python version of 3.6.8, so TriBITS projects + Python support will not work there. RHEL9 has a default Python version of 3.9.18 so that's a-okay. We have a large number of RHEL8 platforms, so that has the potential to cause issues. How strong is the requirement for 3.8+?

It is not a strong requirement at all.  Any version of Python 3.x should be fine (and even Python 2.7 is technically is still supported by the code).  It is just that even Python 3.8 is at end-of-support this month according to https://devguide.python.org/versions/.

I went ahead and downgrade this to 3.6.8 (see commit https://github.com/TriBITSPub/TriBITS/pull/616/commits/6fb7d5e6e078bf6b9d25e80e8c386c2000eb5723).

But note the these SNL RHEL8 machines seem to also have Python 3.12.3 installed by default under `/usr/bin/python3.12` as well:

```
$ /usr/bin/python3.12 --version
Python 3.12.3
```

I am wondering if we should not be more pro-active and push the version of Python3 being used and supported to a more recent version?  According to https://devguide.python.org/versions/, Python 3.12 should be supported through 2028.  Just a thought.

**Comment by bartlettroscoe** [comment]
FYI: Note that on SNL RHEL8 machines, `find_package(Python3)` finds Python 3.12, not 3.6 as shown by the TriBITS configure output:

```
-- Found Python3: /usr/bin/python3.12 (found suitable version "3.12.3", minimum required is "3.6") found components: Interpreter 
-- Python3_EXECUTABLE='/usr/bin/python3.12'
```

So unless you explicitly configure with `-D Python3_EXECUTABLE=$(which python3)`, people will be using and testing with Python 3.12 anyway.

**Comment by sebrowne** [comment]
While that is valid, that package is an optional (additional) installation.  So the question is "Should this support RHEL8 _default_ Python?"  I'm fine with the proposed approach now that you've noticed that Python 3.12 is installed on the RHEL8 machines that we care about the most.  It will make us install that package in our UBI8 containers as well, but we can do that.

**Review by sebrowne — APPROVED** [review]

**Comment by bartlettroscoe** [comment]
> While that is valid, that package is an optional (additional) installation. So the question is "Should this support RHEL8 _default_ Python?" I'm fine with the proposed approach now that you've noticed that Python 3.12 is installed on the RHEL8 machines that we care about the most. It will make us install that package in our UBI8 containers as well, but we can do that.

I think this is really a decision for the Trilinos Leadership team and close Trilinos stakeholders.  TriBITS does not have much of a dependence on Python.  (You can build test your software with just raw CMake/CTest 3.23+.)  Python is just gravy for TriBITS.

I will go ahead and merge this.

**Review by rabartlett1972 — APPROVED** [review]
@sebrowne approved so I will allow to merge.

**Pull request merged**
