### PR TITLE
Resolves "gitdist:  Add Default Development Branch Support

### LINKED ISSUE #235: gitdist:  Add Default Development Branch Support
@bartlettroscoe, I had a realization while driving home today.  The reason we as applications wanted to stay on a `master`/`develop` workflow&mdash;the reason for all the git trickery of renaming `develop` to `real-develop` and then creating a new `develop` branch for the application&mdash;was coming at least in part from a desire to use `gitdist`.  For instance, if the application fork of Trilinos were to have the usual `master` and `develop` branches, and then a `app-dev` branch along the lines of what you showed for ROL, an app developer would have to do the following:
```bash
gitdist checkout develop
cd <trilinosLocation>
git checkout app-dev
gitdist checkout -b <featureBranch>
# do some work
```

and that little extra you need to do for Trilinos would be frustrating and easy to forget.

My earlier solution was all the git trickery in the application fork of Trilinos, but I realized we could solve the same problem in `gitdist` instead.  Suppose we add some way to configure `gitdist` such that you can specify the main development branch in all the repos you're using `gitdist` to manage.  I don't know if this would belong in the `.gitdist` file or elsewhere.  Then we could add a command to `gitdist` to check out that default branch in all repos.  For instance:
```bash
gitdist checkout-default-branch
gitdist checkout -b <featureBranch>
# do some work
```

Alternatively we may be able to do something along the lines of what you did with the repo version file, such that `gitdist checkout __DEFAULT_BRANCH__` would understand what you meant.  Actually I think I like this better, because we could also figure out how to `gitdist merge __DEFAULT_BRANCH__` or `gitdist rebase __DEFAULT_BRANCH__`, etc.

I can try to whip something up in the morning.

### PR DESCRIPTION
**Pull request by jmgate**
Here's an initial implementation that allows a user to pass `_DEFAULT_BRANCH_` to any command that would normally take a reference (branch, tag, SHA1).  Users can set up their `.gitdist` file as follows:
```
. master
someRepo develop
anotherRepo app-dev
# etc
```

The lines of the file are read and then split on spaces.  The first entry is the path to the repo `gitdist` will be working with.  If there is a second entry, that will be substituted any time `_DEFAULT_BRANCH_` is used on the command line.  If no second entry exists, the `master` branch is assumed.

This allows for the following workflow:
```bash
gitdist checkout _DEFAULT_BRANCH_
gitdist checkout -b <featureBranch>
# do some work
gitdist fetch
gitdist rebase origin/_DEFAULT_BRANCH_
# etc.
```

There may be a better way to implement this, but this at least gets us started.

Closes #235

### CODE REVIEW

**Comment by jmgate** [comment]
@bartlettroscoe, I'm pretty sure the work on this PR is finished now.

**Comment by bartlettroscoe** [comment]
@jmgate, okay, I will take a look.  Thanks!

**Comment by bartlettroscoe** [comment]
@jmgate,

The changes to gitdist.py look great; very clean.    The unit tests look excellent.  I did not even bother trying to manually test this myself.  I have little doubt that this is working correctly from just looking at the unit tests.  I think this is a nice feature to add to the script.

I added some commits to make some small tweaks to the documentation and add --dist-help=default-branch output to the TriBITS developers guide.  If these changes look okay to you, then I can go ahead and merge and push this branch.

Thanks for doing all of this!

**Comment by jmgate** [comment]
Yup, that all looks fine to me.  Thanks @bartlettroscoe.

**Pull request merged**
