### PR TITLE
Add expected builds filter

### PR DESCRIPTION
**Pull request by e10harvey**
TODOs:

- [x] Remove duplicate commits
- [x] Create option to filter by expected builds file

### CODE REVIEW

**Review by bartlettroscoe — CHANGES_REQUESTED** [review]
@e10harvey, thanks for the PR.  I can see what it is you want to do here.

I will put more details in a comment in:

* https://gitlab-ex.sandia.gov/atdm/TrilinosATDMStatus/-/merge_requests/4

but technically this code is not correct for the general use case (as described in the associated review comments below).

However, I know how to fix this and it will actually involve less new code (because 95% of the functionality needed to do this correctly is already there and unit tested) and will have better scaling (which should reduce algorithmic complexity from `O(n*m)` to `O(n*log(m))`.

I will post a new PR against this PR to fix the issues (with full unit tests).

**Comment by e10harvey** [comment]
> I will post a new PR against this PR to fix the issues (with full unit tests).

Thanks, @bartlettroscoe !

**Comment by bartlettroscoe** [comment]
@e10harvey, please review, approve, and mere https://github.com/e10harvey/TriBITS/pull/1 that will update this PR and then I can approve and merge.

**Review by bartlettroscoe — COMMENTED** [review]
Forgot to approve this after merging in my fixes from https://github.com/e10harvey/TriBITS/pull/1

**Pull request merged**
