### PR TITLE
Try to clean up logic for finding HDF5 to address Nico's concerns (TriBITS #67)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
@nschloe, take a look at this and see if this seems more clear to you.  Hopefully this will address you concerns expressed in #67.

### CODE REVIEW

**Comment by nschloe** [comment]
Much clearer, thanks!

**Comment by bartlettroscoe** [comment]
Excellent.  Then, if you don't mind, can you test the updated `FindTPLHDF5.cmake` for your needs and then I will do the same for CASL VERA? 

Then, if that works out, can you update the `FindTPLBLAS.cmake`


 I will test the new `FindTPLHDF5.cmake` module with

**Comment by bartlettroscoe** [comment]
What I meant to say (before accidentally hitting 'Tab' and 'Enter') was:

----

Excellent.  Then, if you don't mind, can you test the updated `FindTPLHDF5.cmake` for your needs and then I will do the same for CASL VERA? 

Then, if that works out, can you update the `FindTPLBLAS.cmake` and `FindTPLLAPACK.cmake` in #69 to match this?

**Comment by nschloe** [comment]
I'm getting Trilinos build errors for this right now. Investigating...

**Comment by nschloe** [comment]
With this patch, the output from CMake is
```
Processing enabled TPL: HDF5 (enabled explicitly, disable with -DTPL_ENABLE_HDF5=OFF)
-- Using FIND_PACKAGE(HDF5 ...) ...
-- Found HDF5: /usr/lib/x86_64-linux-gnu/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
```
Unfortunately, those libs aren't added on the link line of 
```
libtrilinos_epetraext.so
```
which results in a link error.

Everything works fine on TriBits::master.

**Comment by bartlettroscoe** [comment]
I know what the problem is.  The issue is that `TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES()` is set up to set include dirs and libs base on the arguments REQUIRED_HEADERS and REQUIRED_LIBS_NAMES.

Let me try to reorganize the file so that it works but is also more clear.  I will push the new commit.

**Comment by nschloe** [comment]
I'm hanging tight. :)

**Comment by bartlettroscoe** [comment]
Nico,

Pull the updated commit and try it.  I tested it locally and it should work.  Basically, you can't let the variables `REQUIRED_HEADERS` and `REQUIRED_LIBS_NAMES` passed into ` TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES()`.  That function uses those variables to determine if the TPL is supposed to have include directories or libraries at all.  If you leave them (or set them to) null, then it thinks there are no include directories or no libraries, respectively.

I can think of some ways to refactor this code to allow you to leave the variables `REQUIRED_HEADERS` and `REQUIRED_LIBS_NAMES` null when `FIND_PACKAGE(HDF5 ...)` but that will raise some other confusion.

Let me know if this is acceptable or not.  Otherwise, we need to talk about this (over WebEx or Google Hangout) some.

**Comment by nschloe** [comment]
I just tested it and can confirm it's working. Good to go by me.

**Comment by bartlettroscoe** [comment]
Are you satisfied with the structure of the file?

**Comment by nschloe** [comment]
It's not clear from the file how TriBits finds the libraries if `FIND_PACKAGE()` doesn't, but hey, I can live with that. The rest of the code is clear and descriptive.

**Comment by bartlettroscoe** [comment]
> It's not clear from the file how TriBits finds the libraries if `FIND_PACKAGE()` doesn't, but hey, I can live with that. The rest of the code is clear and descriptive.

Okay, how TriBITS finds libraries without `FIND_PACKAGE()` is something that needs to be better documented.  But that has nothing to do with how `FIND_PACKAGE()` gets used.  Therefore, I will test the updated `FindTPLHDF5.cmake` file some more then push it.  I will also update the limited documentation to be consistent.

**Comment by nschloe** [comment]
Sounds good to me.

**Comment by bartlettroscoe** [comment]
Nico,

I have pushed these changes to the github/master branch and snapshotted to Trilinos in the Trilinos commit:

```
ommit 543e7f64e94edba66f955fedf1adc593f9d7e79c
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Tue May 26 12:40:52 2015 -0400

    Automatic snapshot commit from tribits at d953228
    
    Origin repo remote tracking branch: 'origin/master'
    Origin repo remote repo URL: 'origin = git@github.com:TriBITSPub/TriBITS'
    
    At commit:
    
    commit 7f0d946cf8451a6131d1c9d1ed313170ea84cf53
    Author:  Roscoe A. Bartlett <bartlettra@ornl.gov>
    Date:    Fri May 22 17:57:43 2015 -0400
    Summary: Update documentation to correspond with updated structure (TriBITS #67)

A       cmake/tribits/Copyright.txt
M       cmake/tribits/common_tpls/FindTPLHDF5.cmake
M       cmake/tribits/doc/developers_guide/TribitsDevelopersGuide.rst
```

**Pull request merged**
