### PR TITLE
Resolve "Make SnapshotDir Python 3 Compatible"

### LINKED ISSUE #310: Make SnapshotDir Python 3 Compatible
Part of #309. 

I'll take a crack at making `SnapshotDir.py` and `snapshot-dir.py` Python 3 compatible.  The issues I've noticed so far at the byte-to-string conversion issues, so I imagine we need to do something along the lines of what was done for `b(x)` and `s(x)` at the top of `gitdist.py`.  There may be other issues, e.g., syntax for `print` or raising exceptions.

### PR DESCRIPTION
**Pull request by jmgate**
Wrap `getCmndOutput()` in `s()` to decode bytestrings in Python 3.

Closes #310.

@bartlettroscoe, I think this is all that's needed for this particular script.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Thanks @jmgate!  Let's see what the TravisCI tseting showed with Python 2.7 and then we can merge.

**Comment by jmgate** [comment]
Is TavisCI no longer running?

**Comment by bartlettroscoe** [comment]
> Is TavisCI no longer running?

Good question.

For now, I will test this and PR #308 locally and push both at the same time.

**Comment by bartlettroscoe** [comment]
> Is TavisCI no longer running?

Travis CI is running the nightly builds as shown here:

* https://travis-ci.org/github/TriBITSPub/TriBITS/builds

but it does not seem to be testing PRs for some reason.

**Comment by bartlettroscoe** [comment]
I tested this locally with Python 2.6.6 (which is the default on RHEL6) and it sitll passed somehow.  I submitted this to CDash here:

* https://testing.sandia.gov/cdash/index.php?project=TriBITS&parentid=6697019

using 

```
$ make dashboard
```

The result for the SnapshotDir test is shown here:

* https://testing.sandia.gov/cdash/testDetails.php?test=106971844&build=6697020

which shows it running:

```
Running: "/usr/bin/python" "/ascldap/users/rabartl/Trilinos.base/Trilinos/TriBITS/test/python_utils/SnapshotDir_UnitTests.py" "-v"
```

That is Python 2.6.6 on that machine which you can see in [this test](https://testing.sandia.gov/cdash/testDetails.php?test=106971580&build=6697020) which shows:

```
Configuring TribitsHelloWorld build directory

...

-- Found PythonInterp: /usr/bin/python (found suitable version "2.6.6", minimum required is "2.6") 
-- PYTHON_EXECUTABLE='/usr/bin/python'
```

So this does not break backward compatibility with Python 2.6.6. 

I did not think that Python 2.6 had the `argparse` package.  Go figure.

**Pull request merged**
