### PR TITLE
Resolve "snapshot-dir.py:  Add --exclude Option"

### LINKED ISSUE #307: snapshot-dir.py:  Add --exclude Option
Part of #48.

I'd like `snapshot-dir.py` to have the ability to exclude files or directories when snapshotting.  As part of [compadre#164](https://github.com/SNLComputation/compadre/issues/164), I want to be able to snapshot part of Compadre into Trilinos, but I want to exclude certain directories and files.  I could write my own wrapper script in Compadre ([compadre#175](https://github.com/SNLComputation/compadre/issues/175)), but I'd prefer if the core functionality lived in `snapshot-dir.py` itself.

@bartlettroscoe, I'll start hacking away at this.  If there are particular design considerations you have in mind, please let me know.

### PR DESCRIPTION
**Pull request by jmgate**
Closes #307 

Tested manually and it does the right thing.  Haven't created a test for it yet.

### CODE REVIEW

**Comment by jmgate** [comment]
Added tests.  @bartlettroscoe, I think this is ready for review.

**Comment by bartlettroscoe** [comment]
>  I think this is ready for review.

@jmgate, let's see what the Travis CI build shows and then I will review and test manually locally.

Note from [this Travis CI build](https://travis-ci.org/github/TriBITSPub/TriBITS/builds/663990498?utm_source=github_status&utm_medium=notification):

```
-- Found PythonInterp: /opt/pyenv/shims/python (found suitable version "2.7.6", minimum required is "2.6") 
PYTHON_EXECUTABLE = /opt/pyenv/shims/python
```

so ti looks like Travis CI is actually testing with Python 2.7, not 2.6.  That means that going forward (unless I do the work to downgrade Python to 2.7) that TriBITS testing is really only testing Python 2.7 and TriBITS can not really be supporting Python 2.6 anymore.  I will have to adjust my local testing env on my RHEL6 machine to test with Python 2.7.

**Comment by jmgate** [comment]
@bartlettroscoe, this look good to you?

**Comment by bartlettroscoe** [comment]
Wow, 'argsparse' --help looks great:

```
usage: snapshot-dir.py [-h] [--show-defaults] [--orig-dir ORIGDIR]
                       [--dest-dir DESTDIR]
                       [--exclude [EXCLUDE [EXCLUDE ...]]]
                       [--assert-clean-orig-dir] [--allow-dirty-orig-dir]
                       [--assert-clean-dest-dir] [--allow-dirty-dest-dir]
                       [--clean-ignored-files-orig-dir]
                       [--no-clean-ignored-files-orig-dir] [--do-rsync]
                       [--skip-rsync] [--do-commit] [--skip-commit]

This tool snapshots the contents of an origin directory ('orig-dir') to
destination directory ('dest-dir') and creates linkages between the two git
repos in the commit message in the 'dest-dir' git branch.  The command 'git'
must be in the path for this script to be used.
```

**Pull request merged**
