### PR TITLE
enable COMPONENT logic for export files

### PR DESCRIPTION
**Pull request by nschloe**
This picks up [Trilinos bug #5900](https://software.sandia.gov/bugzilla/show_bug.cgi?id=5900).

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Any more testing needed before I merge and push this?

**Comment by nschloe** [comment]
I would like to test this, but SEACAS doesn't built atm (cf. https://software.sandia.gov/bugzilla/show_bug.cgi?id=6337). Once that error is fixed, I'll build Nosh, lifeV, Albany against this PR.

**Comment by nschloe** [comment]
Just tested with Albany and Nosh, everything links and compiles fine.

**Comment by bartlettroscoe** [comment]
I will pull this and test this against CASL VERA and make sure it does not break that (but I don't think CASL VERA even uses this file but I will make sure). 

-Ross

**Comment by bartlettroscoe** [comment]
I rebased this branch and merged and pushed it.  This change has been pushed in the commit:

```
commit 6cd3d802068592ad65c1aa46e155ac9610188e71
Author: Nico Schlömer <nico.schloemer@gmail.com>
Date:   Thu Apr 9 12:12:10 2015 +0200

    enable COMPONENT logic for export files

M       tribits/core/installation/TribitsProjectConfigTemplate.cmake.in
M       tribits/core/package_arch/TribitsWriteClientExportFiles.cmake
```

**Comment by nschloe** [comment]
Thanks! I just tested and it's working as expected.

**Pull request closed without merging**
