### PR TITLE
#377: Fixing typos

### PR DESCRIPTION
**Pull request by marcinwrobel1986**
Addresses #377

### This PR:
- fixes text typos in:
  - tribits/core/package_arch/TribitsReadAllProjectDepsFilesCreateDepsGraph.cmake
  - tribits/core/package_arch/TribitsReadDepsFilesCreateDepsGraph.cmake
  - tribits/core/package_arch/TribitsSystemDataStructuresMacrosFunctions.rst
- there are still typos in functions and variables names, but I would leave that to @bartlettroscoe

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
> there are still typos in functions and variables names, but I would leave that to @bartlettroscoe

@marcinwrobel1986, please go ahead and make any name changes you want in this PR.  I will make sure nothing breaks before the merge.

**Comment by marcinwrobel1986** [comment]
@bartlettroscoe Hello Ross, I think it's ready to be reviewed

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Hello Ross, I think it's ready to be reviewed

Thanks @marcinwrobel1986!  I will take care of this after #389 (which will test this automatically :-))

**Review by bartlettroscoe — APPROVED** [review]
I suspect this may conflict with PR #403 but I will take care of those conflicts after this merges.

I really need to run the spell checker on this code base more often to catch things like this.  (But I am not sure it would catch misspellings inside of longer macro/function names like this.)  I guess I just need to be more careful when first writing these to separate out the words and spell check them individually and then concatenate them into the macro/function name.

**Comment by marcinwrobel1986** [comment]
> I suspect this may conflict with PR #403 but I will take care of those conflicts after this merges.

Thanks Ross!

> I really need to run the spell checker on this code base more often to catch things like this. (But I am not sure it would catch misspellings inside of longer macro/function names like this.) I guess I just need to be more careful when first writing these to separate out the words and spell check them individually and then concatenate them into the macro/function name.

An IDE with spell check wouldn't be a bad choice :)

**Comment by bartlettroscoe** [comment]
> An IDE with spell check wouldn't be a bad choice :)

Yea, it may be time to look into that, even if it is just inside of emacs.  (Getting an IDE to work on all of the various SNL machines is very difficult.)

**Comment by marcinwrobel1986** [comment]
Hello Ross, I don't use emacs, but I have found something. Maybe it's worth to give it a try:
[Spell Checking in Emacs](https://www.tenderisthebyte.com/blog/2019/06/09/spell-checking-emacs/)

**Pull request merged**
