### PR TITLE
#116 - inlining winmath.h tgammaf, tgamma, tgammal, and erff

### PR DESCRIPTION
**Pull request by lefebvrera**
Needed changes to remove link error on windows when also using cmath.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Is `inline` a valid keyword in the C standard?  It looks like Trilinos currently only includes this file in C++ code (as shown below) so this should be okay for Trilinos.  But I am concerned that there may be some clients of Trilinos that might have C files that might include these headers.  I think there is a small chance of that given that about all of the clients of Trilinos are likely C++ codes.

Therefore, I think there is only a very small chance that this change will cause any trouble.

Therefore, I will push this change to the casl-dev  and GitHub repos for TriBITS, but I will only test against CASL VERA and not all of Trilinos.  I will not snapshot this into Trilinos until I can test all of the effected software shown below (but that will not impact CASL anyway because we have not synced Trilinos to casl-dev in a long time).

```
$ cd Trilinos/
$ find . -name "*pp" -exec grep -nH winmath {} \;
./packages/intrepid2/refactor/src/Shared/later/Intrepid2_BurkardtRulesDef.hpp:51:#include "winmath.h"
./packages/intrepid2/refactor/src/Shared/later/Intrepid2_PointToolsDef.hpp:48:#include "winmath.h"
./packages/intrepid2/refactor/src/Shared/later/Intrepid2_PolylibDef.hpp:94:#include "winmath.h"
./packages/intrepid2/core/src/Shared/Intrepid2_BurkardtRulesDef.hpp:51:#include "winmath.h"
./packages/intrepid2/core/src/Shared/Intrepid2_PointToolsDef.hpp:48:#include "winmath.h"
./packages/intrepid2/core/src/Shared/Intrepid2_PolylibDef.hpp:94:#include "winmath.h"
./packages/sacado/test/tradoptest/tradoptest_45.cpp:13:#include "winmath.h"
./packages/sacado/test/tradoptest/tradoptest_47.cpp:13:#include "winmath.h"
./packages/sacado/test/tradoptest/tradoptest_43.cpp:13:#include "winmath.h"
./packages/rythmos/test/ConvergenceTest/Rythmos_ConvergenceTestHelpers.cpp:32:#include "winmath.h"
./packages/intrepid/src/Shared/Intrepid_PolylibDef.hpp:95:#include "winmath.h"
./packages/intrepid/src/Shared/Intrepid_PointToolsDef.hpp:49:#include "winmath.h"
./packages/intrepid/src/Shared/Intrepid_BurkardtRulesDef.hpp:52:#include "winmath.h"
```

**Comment by bartlettroscoe** [comment]
Putting in link to #116.

**Comment by lefebvrera** [comment]
Ross, per C99 standard, inline functions are valid.

C99 standard (ISO/IEC 9899:1999):
6.7.4 Function specifiers (p: 112-113)

**Comment by bartlettroscoe** [comment]
> Ross, per C99 standard, inline functions are valid.

Good.  When I searched for keywords in C, 'inline' was not listed.  I must have found the C89 standard.

I rebased this commit and pushed it as caa5223 to the master branches in the casl-dev and this GitHub repo.  I tested this against all of CASL VERA with:

```
$ /checkin-test-vera.sh --test-categories=BASIC --enable-all-packages=on --do-all --push
```
and it passed and push.

**Pull request closed without merging**
